Repository tbf-challenge/teamwork-be, pull requests merged in 2022-08, with the labels that each got.

#55 add script for migrations
  .env.sample
  README.md
  migrations/1660111562812_db-init.js
  package-lock.json
  package.json
  src/config.js
  src/db/index.js
  src/scripts/seeddb.js
  src/server.js
Labels: backend

#75 initialize the database again
  migrations/1660757644069_db-init.js
Labels: chore

#56 feature(endpoint): create article endpoint [start #45]
  migrations/1660757644069_db-init.js
  src/app.js
  src/routes/index.js
  src/routes/posts.js
Labels: backend

#58 Ft get articles endpoint 57
  src/routes/index.js
  src/routes/posts.js
Labels: backend

#64 Ft delete article endpoint 63
  src/routes/posts.js
Labels: backend

#62 Ft update article endpoint 61
  src/routes/posts.js
Labels: backend

#60 Ft get an article 59
  src/routes/posts.js
Labels: backend

#65 add sign up and login endpoints
  .env.sample
  .eslintrc.json
  README.md
  migrations/1660757644069_db-init.js
  migrations/1661147954049_alter-email-make-unique.js
  package-lock.json
  package.json
  src/app.js
  src/config.js
  src/db/index.js
  src/lib/app-error.js
  src/lib/catch-async.js
  src/lib/index.js
  src/lib/logger.js
  src/lib/passport-jwt.js
  src/lib/passport-local.js
  src/lib/passwordlib.js
  src/lib/schema.js
  src/lib/status-codes.js
  src/middleware/global-errorhandler.js
  src/middleware/validateSchema.js
  src/routes/auth.js
  src/routes/index.js
  src/routes/posts.js
  src/routes/users.js
  src/scripts/seeddb.js
  src/server.js
  src/services/users.js
Labels: backend

#81 add reject unauthorised for secure connection
  package-lock.json
  package.json
  src/app.js
  src/db/index.js
  src/lib/logger.js
Labels: backend

#67 Ft create comment endpoint 66
  src/routes/posts.js
Labels: backend

#83 fix Error: router.route is not a function
  src/routes/posts.js
Labels: bug, backend

#90 enhancement(x): enhanced create post endpoint properties [Start #88]
  src/routes/articles.js
  src/routes/index.js
  src/routes/posts.js
  src/services/posts.js
Labels: enhancement, backend

#98 enhancement(x): enhanced the get article properties [Start #97]
  src/routes/articles.js
  src/routes/posts.js
  src/services/posts.js
Labels: enhancement, backend

#100 enhancement(x):enhanced comment properties [Start #99]
  src/routes/articles.js
  src/routes/posts.js
  src/services/errors.js
  src/services/posts.js
Labels: enhancement, backend

#103 enhancement(x): enhanced update article properties [Start #102]
  src/routes/articles.js
  src/routes/posts.js
  src/services/errors.js
  src/services/posts.js
Labels: enhancement, backend

#105 refactor(endpoint): refactored delete endpoint [Start #104]
  src/routes/articles.js
  src/routes/posts.js
  src/services/posts.js
Labels: enhancement, backend
