Repository tbf-challenge/teamwork-be, pull requests merged in 2022-09, with the labels that each got.

#107 Doc add documentation
  docs/swagger.yaml
  package-lock.json
  package.json
  src/app.js
Labels: chore

#112 feature(format):Legible password format [Start #96]
  src/lib/schema.js
Labels: bug, backend

#114 refactor(x): refactor delete tags to use services [Start #113]
  src/routes/articles.js
  src/routes/posts.js
  src/services/posts.js
Labels: enhancement, backend

#116 refactor(x) refactor get articles with same tag [Start #115]
  src/routes/articles.js
  src/routes/posts.js
  src/services/posts.js
Labels: enhancement, backend

#118 refactor(x): refactor assign tag to post to use services [Start #117]
  src/lib/custom-error.js
  src/routes/articles.js
  src/routes/posts.js
  src/services/errors.js
  src/services/posts.js
  src/services/tags.js
Labels: enhancement, backend

#120 feature(validation): validate article updates [Start #119]
  src/db/index.js
  src/lib/index.js
  src/lib/schema.js
  src/middleware/global-errorhandler.js
  src/middleware/validateSchema.js
  src/routes/articles.js
  src/routes/auth.js
  src/schema.js
  src/server.js
Labels: backend

#122 feature(validation): validate create comment data [Start #121]
  src/routes/articles.js
  src/schema.js
Labels: backend

#128 feature(validation): validate create tag data [Start #127]
  src/routes/tags.js
  src/schema.js
Labels: backend

#131 feature(validation): validate update tag data [Start #129]
  src/routes/tags.js
  src/schema.js
Labels: backend

#133 feature(validation): validate delete tag data [Start #132]
  src/routes/tags.js
  src/schema.js
Labels: backend

#136 feature(validation): validate assign tag to article requests [Start #…
  src/routes/articles.js
  src/schema.js
Labels: backend

#138 feature(validation): validate delete tag request [Start #137]
  src/routes/articles.js
  src/schema.js
Labels: backend

#140 feature(validation): validate query article tag request [Start #139]
  src/routes/articles.js
  src/schema.js
Labels: backend

#149 Rf query code assign tags article 147
  src/routes/posts.js
  src/services/posts.js
Labels: bug, backend

#152 refactor(x): refactor code for creating tags [Start #150]
  migrations/1661202676736_drop-content-and-title-columns-from-posts-tags-table.js
  migrations/1662648153132_create-unique-constraint-for-title-in-tags-table.js
  src/services/tags.js
Labels: bug, backend

#167 feature(x):make certain fields optional on users table [Start #160]
  migrations/1662985386038_make-certain-fields-optional-on-users-table.js
  src/schema.js
Labels: bug, backend

#168 feature(x): make content column optional in tags table [Start #154]
  migrations/1663002357449_make-content-column-optional-in-tags-table.js
  src/schema.js
Labels: bug, backend

#170 feature(x):add table to record invited users [Start #163]
  migrations/1663064650000_add-table-to-record-invited-users.js
Labels: backend

#172 feature(x): setting up testing [Start #159]
  .eslintrc.json
  jest.config.js
  package-lock.json
  package.json
Labels: backend

#173 script to add admin user to database
  package-lock.json
  package.json
  src/scripts/insertAdminUser.js
Labels: backend

#178 update auth flow
  migrations/1663242645298_add-refreshToken-to-user-table.js
  src/routes/auth.js
  src/services/users/generate-access-token.js
  src/services/users/generate-refresh-token.js
  src/services/users/index.js
Labels: backend

#179 add endpoint to get new tokens with refresh token
  src/routes/auth.js
  src/schema.js
  src/services/errors.js
  src/services/users/index.js
  src/services/users/update-refresh-token.js
Labels: backend

#181 Endpoint to get invited user information
  docs/swagger.yaml
  src/routes/auth.js
  src/services/errors.js
  src/services/users/index.js
Labels: backend

#192 newly generated token from auth/token endpoint not working
  src/services/users/index.js
Labels: backend

#193 Add type column to posts table and set existing posts to type article
  migrations/1663764054134_add-type-column-to-posts-table-and-set-existing-posts-to-type-article.js
  src/services/posts.js
Labels: backend

#195 feature(endpoint): create gif endpoint [Start #184]
  docs/swagger.yaml
  src/routes/articles.js
  src/routes/gifs.js
  src/routes/index.js
  src/schema.js
  src/services/posts.js
Labels: backend, task

#196 Setup test utils
  .gitignore
  .mocharc.js
  README.md
  package.json
  src/config.js
  test/pretest.js
  test/utils.js
Labels: backend

#200 Get gif by id
  docs/swagger.yaml
  src/routes/articles.js
  src/routes/gifs.js
  src/services/errors.js
  src/services/posts.js
Labels: backend

#201 feature(endpoint) delete gif endpoint [Start #188]
  docs/swagger.yaml
  package-lock.json
  package.json
  src/routes/articles.js
  src/routes/gifs.js
  src/services/posts/delete-post.js
  src/services/posts/delete-post.test.js
  src/services/posts/index.js
  test/utils.js
Labels: documentation, backend

#205 Endpoint for creating comments on gifs
  docs/swagger.yaml
  src/routes/articles.js
  src/routes/gifs.js
  src/services/errors.js
  src/services/posts/create-comment.js
  src/services/posts/create-comment.test.js
  src/services/posts/index.js
  test/utils.js
Labels: documentation, backend

#214 add record likes table [Start #207]
  migrations/1664273420286_add-table-to-record-likes-on-posts.js
Labels: backend

#215 add table to record flagged posts [Start #208]
  migrations/1664278604452_add-table-to-record-flagged-posts.js
Labels: backend

#216 add record likes to gif endpoint
  docs/swagger.yaml
  src/routes/gifs.js
  src/schema.js
  src/services/errors.js
  src/services/posts/index.js
  src/services/posts/like-post.js
  src/services/posts/like-post.test.js
  test/utils.js
Labels: backend

#218 record likes on article endpoint
  docs/swagger.yaml
  src/routes/articles.js
  src/routes/gifs.js
  src/schema.js
  src/services/errors.js
  src/services/posts/like-post.js
  src/services/posts/like-post.test.js
Labels: backend

#219 Endpoint for unliking a gif
  .mocharc.js
  docs/swagger.yaml
  src/routes/gifs/index.js
  src/routes/gifs/unlike-gif.e2e.test.js
  src/schema.js
  src/services/posts/index.js
  src/services/posts/unlike-post.js
  src/services/posts/unlike-post.test.js
  test/utils.js
Labels: backend
