Repository tbf-challenge/teamwork-be, pull requests merged in 2022-11, with the labels that each got.

#286 get user invite information test
  docs/swagger.yaml
  src/routes/auth/get-invited-user-detail.e2e.test.js
  src/services/users/get-invited-user-detail.js
  src/services/users/get-invited-user-detail.test.js
  src/services/users/index.js
  test/utils.js
Labels: backend

#289 create gif endpoint test
  docs/swagger.yaml
  src/routes/gifs/create-gif.e2e.test.js
  src/routes/gifs/index.js
Labels: backend

#291 delete article endpoint test
  src/routes/articles/delete-article.e2e.test.js
  src/services/posts/delete-post.test.js
Labels: backend

#293 get article test
  src/routes/articles/get-article.e2e.test.js
  src/services/posts/get-post.js
  src/services/posts/get-post.test.js
  src/services/posts/index.js
  test/utils.js
Labels: backend

#295 delete gif endpoint test
  src/routes/gifs/delete-gif.e2e.test.js
Labels: backend

#297 update tag testing
  src/routes/tags/update-tag.e2e.test.js
  src/services/tags/index.js
  src/services/tags/update-tag.js
  src/services/tags/update-tag.test.js
Labels: backend

#300 add logs to flaky test
  src/routes/articles/create-article.e2e.test.js
Labels: chore

#299 update the security in the documentation with bearerAuth
  docs/swagger.yaml
Labels: documentation

#303 fixed flaky test for tags
  src/routes/tags/fetch-tags.e2e.test.js
  src/services/tags/fetch-tags.test.js
Labels: backend

#311 return specific fields on posts table
  src/services/posts/create-comment.js
  src/services/posts/create-post.js
  src/services/posts/flag-post.js
  src/services/posts/get-post.js
  src/services/posts/like-post.js
  src/services/posts/update-post.js
Labels: backend

#312 add likes count column on post
  migrations/1668021210259_add-new-column-to-track-likes-on-a-post.js
  src/services/posts/create-comment.test.js
  test/utils.js
Labels: backend

#313 added flagsCount to posts table
  migrations/1668068510139_add-flagsCount-column-to-posts-table.js
Labels: backend

#302 create tag endpoint/service test
  package.json
  src/routes/tags/create-tag.e2e.test.js
  src/services/tags/create-tag.js
  src/services/tags/create-tag.test.js
  src/services/tags/index.js
  test/utils.js
Labels: backend

#274 Invite user endpoint and service test
  .mocharc.js
  package-lock.json
  package.json
  src/lib/email-lib.js
  src/routes/auth/invite-user.e2e.test.js
  src/services/email-templates.js
  src/services/users/index.js
  src/services/users/invite-user.js
  src/services/users/invite-user.test.js
  test/stub-mailer.js
Labels: backend

#314 record number of likes
  migrations/1668360468072_add-trigger-function-to-compute-likesCount-on-posts.js
  src/services/posts/like-post.js
  src/services/posts/like-post.test.js
  src/services/posts/unlike-post.js
  src/services/posts/unlike-post.test.js
Labels: backend

#315 record number of flags
  migrations/1668439124477_add-trigger-function-to-compute-flagsCount-on-posts.js.js
  src/services/posts/flag-post.js
  src/services/posts/flag-post.test.js
  src/services/posts/unflag-post.js
  src/services/posts/unflag-post.test.js
Labels: backend

#321 add test to like gif endpoint
  src/routes/gifs/like-gif.e2e.test.js
Labels: backend

#323 add likes count to get gif endpoint 320
  docs/swagger.yaml
  src/routes/common/transformers.js
Labels: backend

#325 added test to get gif endpoint
  src/routes/gifs/get-gif.e2e.test.js
Labels: backend

#328 add likesCount to get feed endpoint 327
  docs/swagger.yaml
  src/services/posts/index.js
Labels: backend

#329 query all flagged post 326
  docs/swagger.yaml
  src/routes/common/transformers.js
  src/routes/fetch-posts.e2e.test.js
  src/routes/posts.js
  src/schema.js
  src/services/posts/fetch-posts.js
  src/services/posts/fetch-posts.test.js
  src/services/posts/index.js
  test/utils.js
Labels: backend
