Repository tbf-challenge/teamwork-be, pull requests merged in 2022-10, with the labels that each got.

#221 Add contributing.md
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#229 unexpected error about email
  src/routes/auth.js
Labels: backend

#232 flag article endpoint
  docs/swagger.yaml
  src/routes/articles/flag-article.e2e.test.js
  src/routes/articles/index.js
  src/services/errors.js
  src/services/posts/flag-post.js
  src/services/posts/flag-post.test.js
Labels: backend

#238 made additions to response body of auth/signin
  docs/swagger.yaml
  src/routes/auth/index.js
  src/services/users/index.js
Labels: documentation, backend

#240 seed the db with predefined tags
  migrations/1665144863994_seed-db-with-predefined-tags.js
Labels: backend

#251 Include profile picture in create-user endpoint
  docs/swagger.yaml
  migrations/1665421285794_add-profilePictureUrl-column-to-users-table.js
  src/routes/auth/create-new-user.e2e.test.js
  src/routes/auth/index.js
  src/schema.js
  src/services/users/create-new-user.js
  test/utils.js
Labels: documentation, backend

#253 resolved invalid refreshToken bug
  src/services/users/index.js
  src/services/users/update-refresh-token.js
Labels: backend

#247 update documentation with up to date documentation
  docs/swagger.yaml
Labels: documentation, backend

#260 get all employees endpoint
  docs/swagger.yaml
  src/routes/common/transformers.js
  src/routes/users/fetch-users.e2e.test.js
  src/routes/users/index.js
  src/services/users/fetch-users.js
  src/services/users/fetch-users.test.js
  src/services/users/index.js
  test/utils.js
Labels: backend

#263 create article endpoint test
  src/routes/articles/create-article.e2e.test.js
  src/services/posts/create-post.js
  src/services/posts/create-post.test.js
  src/services/posts/index.js
Labels: backend

#265 get tags endpoint test
  src/routes/tags/fetch-tags.e2e.test.js
  src/services/tags/fetch-tags.js
  src/services/tags/fetch-tags.test.js
  src/services/tags/index.js
  test/utils.js
Labels: backend

#267 Update article endpoint testing
  src/routes/articles/update-article.e2e.test.js
  src/services/posts/index.js
  src/services/posts/update-post.js
  src/services/posts/update-post.test.js
Labels: backend

#272 resolve auth token bug
  src/routes/auth/index.js
Labels: bug

#279 added userId to the feed endpoint
  docs/swagger.yaml
  src/routes/posts.js
  src/services/posts/index.js
Labels: backend

#285 resolved bug in the POST articles/gifs
  src/routes/articles/create-article.e2e.test.js
  src/schema.js
Labels: bug, backend

#284 allow failed jobs to run to completions
  .github/workflows/test.yml
Labels: chore, backend

#282 fix flaky test
  src/routes/articles/create-article.e2e.test.js
  src/routes/articles/update-article.e2e.test.js
  src/routes/auth/create-new-user.e2e.test.js
  src/routes/users/update-user.e2e.test.js
  src/schema.js
  test/utils.js
Labels: chore
